import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kevin Carbajal
 */
public class mainXorUI extends javax.swing.JFrame {
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    /**
     * Creates new form mainXorUI
     */
    public mainXorUI() {
        initComponents();
    }
    
    public String abrirArchivo(File archivo){
          String documento = "";
          try {
              entrada = new FileInputStream(archivo);
              int ascii;
              while((ascii=entrada.read())!= -1){
                  char caracter=(char)ascii;
                  documento+=caracter;
              }
          }catch(Exception e){
                      
                      }
            try {
                byte ptext[] = documento.getBytes("ISO-8859-1"); 
                String value = new String(ptext, "UTF-8"); 
                
                //byte ptext[] = documento.getBytes();
                //String value = new String(ptext, "UTF8");
                System.out.println("LOGRADO");
                return value; 
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(mainXorUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            return documento;      
    }
        public String guardarArchivo(File archivo, String documento){
          String mensaje = null;
          try {
              salida = new FileOutputStream(archivo);
              byte[] bytxt=documento.getBytes();
              salida.write(bytxt);
              mensaje = "Archivo guardado";
          }catch(Exception e){
                      
                      }
          return mensaje;     
    }
        
      public String cifrarXor(String texto, String clave){

         char[] ClaveArray=clave.toCharArray(); //hacemos un arreglo de caracteres con esa string
         char[] textoArray=texto.toCharArray();
         
         /*for(int i=0; i<textoArray.length; i++){
             System.out.print(textoArray[i]+",");
         }*/
         System.out.println();
         int textoLen=textoArray.length;
         int claveLen=ClaveArray.length;
         
         char[] nuevoTexto=new char[textoLen]; //reservara un arreglo con el tabaño de la longitud del texto

         for (int i=0; i<textoLen; i++){
           nuevoTexto[i]=(char)(textoArray[i]^ClaveArray[i%claveLen]); //El modulo servira para iterar la clave
         }
         /*for(int i=0; i<textoArray.length; i++){
             System.out.print(nuevoTexto[i]+",");
         }*/
         
         String temp = new String(nuevoTexto);
         return temp;
      
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recibeTextoLlano = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        recibeTextoDescifrar = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        muestraTextoCifrado = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        muestraTextoDescifrar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Abrir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        textoClave = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criptografia");
        setLocation(new java.awt.Point(200, 100));
        setMinimumSize(new java.awt.Dimension(922, 480));
        setPreferredSize(new java.awt.Dimension(922, 505));
        setResizable(false);
        setSize(new java.awt.Dimension(930, 495));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CIFRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 230, 100, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("DESCIFRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 270, 120, 30);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CIFRADO DE VERMAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 20, 270, 40);

        recibeTextoLlano.setColumns(20);
        recibeTextoLlano.setRows(5);
        jScrollPane2.setViewportView(recibeTextoLlano);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 310, 150);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserte el texto a descifrar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 270, 270, 40);

        recibeTextoDescifrar.setColumns(20);
        recibeTextoDescifrar.setRows(5);
        jScrollPane4.setViewportView(recibeTextoDescifrar);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 300, 310, 150);

        muestraTextoCifrado.setColumns(20);
        muestraTextoCifrado.setRows(5);
        jScrollPane3.setViewportView(muestraTextoCifrado);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(560, 120, 330, 150);

        muestraTextoDescifrar.setColumns(20);
        muestraTextoDescifrar.setRows(5);
        jScrollPane5.setViewportView(muestraTextoDescifrar);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(560, 300, 330, 150);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inserte el texto a cifrar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 270, 40);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inserte clave");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 90, 180, 40);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Texto descifrado");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 270, 270, 40);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Texto cifrado");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 80, 270, 40);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel7.setText("Texto cifrado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 80, 200, 40);

        Abrir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Abrir.setText("ABRIR");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        getContentPane().add(Abrir);
        Abrir.setBounds(380, 320, 120, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("GUARDAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 370, 120, 30);

        textoClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClaveActionPerformed(evt);
            }
        });
        getContentPane().add(textoClave);
        textoClave.setBounds(350, 130, 180, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("LIMPIAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(380, 420, 120, 30);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gray.PNG"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, -10, 930, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.muestraTextoCifrado.setText(this.cifrarXor(this.recibeTextoLlano.getText(), this.textoClave.getText()));
        this.recibeTextoDescifrar.setText(this.cifrarXor(this.recibeTextoLlano.getText(), this.textoClave.getText()));
        //System.out.println(this.recibeTextoCifrado.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.muestraTextoDescifrar.setText(this.cifrarXor(this.recibeTextoDescifrar.getText(), this.textoClave.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClaveActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        //ABRIIIIIIIIIIIIIIIIIIIR :D
        if(seleccionar.showDialog(null,"Abrir")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if (archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    
                    String documento = abrirArchivo(archivo);
                    recibeTextoLlano.setText(documento);   
                }
            }
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null,"Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                    String documento = recibeTextoLlano.getText();
                    String mensaje = guardarArchivo(archivo, documento);
                    if(mensaje!=null){
                        JOptionPane.showMessageDialog(null, mensaje);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Archivo no compatible");
                    }
                }
            else {
                JOptionPane.showMessageDialog(null, "Guardar mensaje de texto"); 
            }
        }           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.muestraTextoCifrado.setText("");
        this.muestraTextoDescifrar.setText("");
        this.recibeTextoDescifrar.setText("");
        this.recibeTextoLlano.setText("");
        this.textoClave.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainXorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainXorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainXorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainXorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainXorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea muestraTextoCifrado;
    private javax.swing.JTextArea muestraTextoDescifrar;
    private javax.swing.JTextArea recibeTextoDescifrar;
    private javax.swing.JTextArea recibeTextoLlano;
    private javax.swing.JTextField textoClave;
    // End of variables declaration//GEN-END:variables
}
